### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kei-123456789** [kei-123456789/furima-37977#22]
# フリマアプリのURL
https://furima-37977.herokuapp.com/

# Basic認証のIDとパスワード
ID:admin
Pass:2828

# 出品者用のメールアドレスとパスワード
email:123456@rb
pass:123abc

# 購入者用のメールアドレスとパスワード
email:abc@rb
pass:123abc

**Comment by motomuun** [comment]
@kei-123456789 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**
- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
北海「道」など、「都道府県」まで表示されるように修正をお願いします。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A
